version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8001:8001"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "MobileST!!"
            ACCEPT_EULA: "Y"
