// <auto-generated />
using System;
using LIMSInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LIMSInfrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20180731043840_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LIMSCore.Billing.MpesaTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amount");

                    b.Property<string>("CheckoutRequestID");

                    b.Property<string>("MerchantRequestId");

                    b.Property<string>("ReceiptNumber");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("MpesaTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
