// <auto-generated />
using System;
using LIMSInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LIMSInfrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20181008141718_V3")]
    partial class V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LIMSCore.Billing.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Expires");

                    b.Property<Guid>("ProductId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("LIMSCore.Billing.MpesaTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amount");

                    b.Property<string>("CheckoutRequestID");

                    b.Property<string>("MerchantRequestId");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("ReceiptNumber");

                    b.Property<DateTime>("TransactionDate");

                    b.HasKey("Id");

                    b.ToTable("MpesaTransaction");
                });

            modelBuilder.Entity("LIMSCore.Billing.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime>("DatePaid");

                    b.Property<Guid>("InvoiceId");

                    b.Property<Guid?>("MyPropertyId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MyPropertyId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("LIMSCore.Billing.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("LIMSCore.Billing.Invoice", b =>
                {
                    b.HasOne("LIMSCore.Billing.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMSCore.Billing.Payment", b =>
                {
                    b.HasOne("LIMSCore.Billing.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMSCore.Billing.MpesaTransaction", "MyProperty")
                        .WithMany()
                        .HasForeignKey("MyPropertyId");
                });
#pragma warning restore 612, 618
        }
    }
}
