// <auto-generated />
using System;
using LIMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LIMS.Infrastructure.Migrations
{
    [DbContext(typeof(LIMSCoreDbContext))]
    [Migration("20190128094530_v7")]
    partial class v7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LIMS.Core.Billing.Checkout", b =>
                {
                    b.Property<Guid>("CheckoutId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountPaid");

                    b.Property<DateTime>("CheckoutDate");

                    b.Property<string>("CheckoutRequest");

                    b.Property<Guid>("InvoiceId");

                    b.HasKey("CheckoutId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Checkout");
                });

            modelBuilder.Entity("LIMS.Core.Billing.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateDue");

                    b.Property<double>("InvoiceAmount");

                    b.Property<string>("InvoiceNumber");

                    b.Property<int>("ParcelId");

                    b.Property<string>("Status");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ParcelId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("LIMS.Core.Billing.MpesaTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amount");

                    b.Property<string>("CheckoutRequestID");

                    b.Property<string>("MerchantRequestId");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("ReceiptNumber");

                    b.Property<DateTime>("TransactionDate");

                    b.HasKey("Id");

                    b.ToTable("MpesaTransaction");
                });

            modelBuilder.Entity("LIMS.Core.Billing.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("InvoiceId");

                    b.Property<string>("ModeOfPayment");

                    b.Property<DateTime?>("PaymentDate");

                    b.Property<string>("ReceiptNo");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Administration", b =>
                {
                    b.Property<int>("AdministrationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlockName");

                    b.Property<string>("DistrictName");

                    b.Property<string>("LocationName");

                    b.HasKey("AdministrationId");

                    b.ToTable("Administration");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApartmentName");

                    b.HasKey("ApartmentId");

                    b.ToTable("Apartment");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Beacon", b =>
                {
                    b.Property<int>("BeaconId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BeaconNum");

                    b.Property<string>("BeaconType");

                    b.Property<DateTime>("DateSet")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("Hcoordinate");

                    b.Property<string>("HorizontalDatum");

                    b.Property<string>("VerticalDatum");

                    b.Property<double>("Xcoordinate");

                    b.Property<double>("Ycoordinate");

                    b.HasKey("BeaconId");

                    b.ToTable("Beacon");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Boundary", b =>
                {
                    b.Property<int>("BoundaryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoundaryType");

                    b.HasKey("BoundaryId");

                    b.ToTable("Boundary");
                });

            modelBuilder.Entity("LIMS.Core.Entities.BoundaryBeacon", b =>
                {
                    b.Property<int>("BoundaryId");

                    b.Property<int>("BeaconId");

                    b.HasKey("BoundaryId", "BeaconId");

                    b.HasIndex("BeaconId");

                    b.ToTable("BoundaryBeacon");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApartmentId");

                    b.Property<int>("SpatialUnitId");

                    b.Property<string>("StreetAddress");

                    b.HasKey("BuildingId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("SpatialUnitId");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("LIMS.Core.Entities.BuildingRegulation", b =>
                {
                    b.Property<int>("BuildingRegulationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GCR")
                        .HasColumnName("GCR");

                    b.Property<double>("PCR")
                        .HasColumnName("PCR");

                    b.Property<double>("PlotFrontage");

                    b.HasKey("BuildingRegulationId");

                    b.ToTable("BuildingRegulation");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Charge", b =>
                {
                    b.Property<int>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<double>("InterestRate");

                    b.Property<string>("Lender")
                        .HasColumnName("lender");

                    b.Property<int>("Ranking");

                    b.Property<int>("RepaymentTerm");

                    b.HasKey("ChargeId");

                    b.ToTable("Charge");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Freehold", b =>
                {
                    b.Property<int>("FreeholdId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TenureId");

                    b.HasKey("FreeholdId");

                    b.HasIndex("TenureId")
                        .IsUnique();

                    b.ToTable("Freehold");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("County");

                    b.Property<string>("GroupType");

                    b.Property<int>("OwnerId");

                    b.HasKey("GroupId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("LIMS.Core.Entities.GroupGroupLeadership", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<int>("GroupLeadershipId");

                    b.HasKey("GroupId", "GroupLeadershipId");

                    b.HasIndex("GroupLeadershipId");

                    b.ToTable("GroupGroupLeadership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.GroupGroupMembership", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<int>("GroupMembershipId");

                    b.HasKey("GroupId", "GroupMembershipId");

                    b.HasIndex("GroupMembershipId");

                    b.ToTable("GroupGroupMembership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.GroupLeadership", b =>
                {
                    b.Property<int>("GroupLeadershipId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LeadershipRole");

                    b.Property<DateTime>("LeadershipSince")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LeadershipStatus");

                    b.Property<DateTime>("LeadershipUntil")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PersonId")
                        .HasColumnName("PersonId");

                    b.HasKey("GroupLeadershipId");

                    b.ToTable("GroupLeadership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.GroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("MembershipShare");

                    b.Property<DateTime>("MembershipSince")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MembershipStatus");

                    b.Property<DateTime>("MembershipUntil")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("GroupMembership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.InsitutionLeadership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("MemberSince")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("MemberUntil")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MembershipRole");

                    b.Property<string>("MembershipStatus");

                    b.HasKey("Id");

                    b.ToTable("InsitutionLeadership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InstitutionType");

                    b.HasKey("InstitutionId");

                    b.ToTable("Institution");
                });

            modelBuilder.Entity("LIMS.Core.Entities.InstitutionInstitutionLeadership", b =>
                {
                    b.Property<int>("InstitutionLeadershipId");

                    b.Property<int>("InstitutionId");

                    b.HasKey("InstitutionLeadershipId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("InstitutionInstitutionLeadership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.LandUse", b =>
                {
                    b.Property<int>("LandUseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingRegulationId");

                    b.Property<DateTime?>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LandUseStatus");

                    b.Property<string>("LandUseType");

                    b.Property<string>("RegulationAgency");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ZoneId");

                    b.HasKey("LandUseId");

                    b.HasIndex("BuildingRegulationId");

                    b.HasIndex("ZoneId");

                    b.ToTable("LandUse");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Leasehold", b =>
                {
                    b.Property<int>("LeaseholdId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LeasePeriod")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Lessor");

                    b.Property<int>("TenureId");

                    b.HasKey("LeaseholdId");

                    b.HasIndex("TenureId");

                    b.ToTable("Leasehold");
                });

            modelBuilder.Entity("LIMS.Core.Entities.MapIndex", b =>
                {
                    b.Property<int>("MapIndexId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MapSheetNum");

                    b.HasKey("MapIndexId");

                    b.ToTable("MapIndex");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Mortgage", b =>
                {
                    b.Property<int>("MortgageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<double>("InterestRate");

                    b.Property<string>("Lender");

                    b.Property<int>("Ranking");

                    b.Property<int>("RepaymentTerm");

                    b.HasKey("MortgageId");

                    b.ToTable("Mortgage");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Operation", b =>
                {
                    b.Property<int>("OperationId");

                    b.Property<string>("OperationName");

                    b.Property<int?>("ParcelId");

                    b.HasKey("OperationId");

                    b.HasIndex("ParcelId");

                    b.ToTable("Operation");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("OwnerType");

                    b.Property<string>("PIN")
                        .HasColumnName("PIN");

                    b.Property<string>("PostalAddress");

                    b.Property<string>("TelephoneAddress");

                    b.HasKey("OwnerId");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("LIMS.Core.Entities.OwnershipRight", b =>
                {
                    b.Property<int>("OwnershipRightId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RightType");

                    b.HasKey("OwnershipRightId");

                    b.ToTable("OwnershipRight");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Parcel", b =>
                {
                    b.Property<int>("ParcelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdministrationId");

                    b.Property<double?>("Area");

                    b.Property<int>("LandUseId");

                    b.Property<int>("OwnerId");

                    b.Property<int>("OwnershipRightId");

                    b.Property<string>("ParcelNum")
                        .IsRequired();

                    b.Property<int?>("RateId");

                    b.Property<int>("RegistrationId");

                    b.Property<int>("ResponsibilityId");

                    b.Property<int>("RestrictionId");

                    b.Property<int>("SpatialUnitId");

                    b.Property<int>("TenureId");

                    b.Property<int>("ValuationId");

                    b.HasKey("ParcelId");

                    b.HasIndex("AdministrationId");

                    b.HasIndex("LandUseId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnershipRightId");

                    b.HasIndex("RateId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("ResponsibilityId");

                    b.HasIndex("RestrictionId");

                    b.HasIndex("SpatialUnitId");

                    b.HasIndex("TenureId");

                    b.HasIndex("ValuationId");

                    b.ToTable("Parcel");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Mobile");

                    b.Property<int>("OwnerId");

                    b.Property<string>("PIN");

                    b.Property<string>("PersonType");

                    b.Property<string>("Phone");

                    b.HasKey("PersonId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("LIMS.Core.Entities.PersonGroupLeadership", b =>
                {
                    b.Property<int>("GroupLeadershipId");

                    b.Property<int>("PersonId");

                    b.HasKey("GroupLeadershipId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonGroupLeadership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.PersonGroupMembership", b =>
                {
                    b.Property<int>("GroupMembershipId");

                    b.Property<int>("PersonId");

                    b.HasKey("GroupMembershipId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonGroupMembership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.PersonInstitutionLeadership", b =>
                {
                    b.Property<int>("InstitutionLeadershipId");

                    b.Property<int>("PersonId");

                    b.HasKey("InstitutionLeadershipId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInstitutionLeadership");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Rate", b =>
                {
                    b.Property<int>("RateId");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.HasKey("RateId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jurisdiction");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RegistrationSection");

                    b.Property<string>("RegistrationType");

                    b.Property<string>("TitleNo");

                    b.HasKey("RegistrationId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Reserve", b =>
                {
                    b.Property<int>("ReserveId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ComplianceStatus");

                    b.Property<string>("EnforcingAuthority");

                    b.Property<string>("ReserveType");

                    b.HasKey("ReserveId");

                    b.ToTable("Reserve");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Responsibility", b =>
                {
                    b.Property<int>("ResponsibilityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PerformanceRequirement");

                    b.Property<string>("ResponsibilityType");

                    b.HasKey("ResponsibilityId");

                    b.ToTable("Responsibility");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Restriction", b =>
                {
                    b.Property<int>("RestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChargeId")
                        .HasColumnName("ChargeId");

                    b.Property<int?>("MortgageId")
                        .HasColumnName("MortgageId");

                    b.Property<int?>("ReserveId")
                        .HasColumnName("ReserveId");

                    b.Property<string>("RestrictionType");

                    b.Property<int?>("StatutoryRestrictionId");

                    b.HasKey("RestrictionId");

                    b.HasIndex("ChargeId");

                    b.HasIndex("MortgageId");

                    b.HasIndex("ReserveId");

                    b.HasIndex("StatutoryRestrictionId");

                    b.ToTable("Restriction");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsComplete");

                    b.Property<int>("OperationId")
                        .HasColumnName("OperationId");

                    b.Property<int?>("Progress");

                    b.HasKey("ServiceId");

                    b.HasIndex("OperationId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("LIMS.Core.Entities.SpatialUnit", b =>
                {
                    b.Property<int>("SpatialUnitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Area");

                    b.Property<int>("BoundaryId");

                    b.Property<string>("Label");

                    b.Property<string>("Layer");

                    b.Property<double?>("Length");

                    b.Property<int>("MapIndexId");

                    b.Property<int>("PreliminaryUnitId");

                    b.Property<string>("ReferencePoint");

                    b.Property<int>("SpatialUnitSetId");

                    b.Property<string>("SpatialUnitType");

                    b.Property<int>("SurveyId");

                    b.Property<double?>("Volume");

                    b.HasKey("SpatialUnitId");

                    b.HasIndex("BoundaryId")
                        .IsUnique();

                    b.HasIndex("MapIndexId");

                    b.HasIndex("SpatialUnitSetId");

                    b.HasIndex("SurveyId");

                    b.ToTable("SpatialUnit");
                });

            modelBuilder.Entity("LIMS.Core.Entities.SpatialUnitSet", b =>
                {
                    b.Property<int>("SpatialUnitSetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.HasKey("SpatialUnitSetId");

                    b.ToTable("SpatialUnitSet");
                });

            modelBuilder.Entity("LIMS.Core.Entities.SpatialUnitSetRegistration", b =>
                {
                    b.Property<int>("RegistrationId");

                    b.Property<int>("SpatialUnitSetId");

                    b.HasKey("RegistrationId", "SpatialUnitSetId");

                    b.HasIndex("SpatialUnitSetId");

                    b.ToTable("SpatialUnitSetRegistration");
                });

            modelBuilder.Entity("LIMS.Core.Entities.StatutoryRestriction", b =>
                {
                    b.Property<int>("StatutoryRestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NatureOfRestriction");

                    b.Property<string>("RestrictingAuthority");

                    b.HasKey("StatutoryRestrictionId");

                    b.ToTable("StatutoryRestriction");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompsNo");

                    b.Property<DateTime?>("DateOfEntry")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ParcelId");

                    b.Property<int>("PdpRefNo")
                        .HasColumnName("PDPRefNo");

                    b.Property<string>("PlansNo");

                    b.Property<string>("SurveyorsName");

                    b.Property<string>("TypeOfSurvey");

                    b.HasKey("SurveyId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Tenure", b =>
                {
                    b.Property<int>("TenureId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenureType");

                    b.HasKey("TenureId");

                    b.ToTable("Tenure");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Valuation", b =>
                {
                    b.Property<int>("ValuationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Remarks");

                    b.Property<string>("SerialNo");

                    b.Property<string>("ValuationBookNo");

                    b.Property<DateTime?>("ValuationDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double?>("Value");

                    b.Property<string>("Valuer");

                    b.HasKey("ValuationId");

                    b.ToTable("Valuation");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ZoneType");

                    b.HasKey("ZoneId");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("LIMS.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("IDNumber");

                    b.Property<string>("KRAPIN");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("MiddleName");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<byte[]>("Photo");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LIMS.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("IPAddress");

                    b.Property<int>("Users");

                    b.HasDiscriminator().HasValue("ApplicationRole");

                    b.HasData(
                        new
                        {
                            Id = "d3e551ea-64f9-4aef-b1c5-d3ebc3b95ef9",
                            ConcurrencyStamp = "a43e2d26-f39f-4cdc-b879-6db302c3296a",
                            Name = "Authors",
                            NormalizedName = "AUTHORS",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Users = 0
                        },
                        new
                        {
                            Id = "916c6f42-7a52-425a-8126-68ade9fe3535",
                            ConcurrencyStamp = "2087ccf2-c35d-4ae8-9000-ec0548b4d263",
                            Name = "Editors",
                            NormalizedName = "EDITORS",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Users = 0
                        },
                        new
                        {
                            Id = "5e43ccc7-d0bb-4489-b239-1f7a9620136e",
                            ConcurrencyStamp = "cb0235ff-2037-400c-8374-ff5e4572b4c8",
                            Name = "Administrators",
                            NormalizedName = "ADMINISTRATORS",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Users = 0
                        });
                });

            modelBuilder.Entity("LIMS.Core.Billing.Checkout", b =>
                {
                    b.HasOne("LIMS.Core.Billing.Invoice", "Invoice")
                        .WithMany("Checkouts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Billing.Invoice", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Parcel", "Parcel")
                        .WithMany("Invoices")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Billing.Payment", b =>
                {
                    b.HasOne("LIMS.Core.Billing.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.BoundaryBeacon", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Beacon", "Beacon")
                        .WithMany("BoundaryBeacons")
                        .HasForeignKey("BeaconId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Boundary", "Boundary")
                        .WithMany("BoundaryBeacons")
                        .HasForeignKey("BoundaryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Building", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Apartment", "Apartment")
                        .WithMany("Building")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.SpatialUnit", "SpatialUnit")
                        .WithMany("Buildings")
                        .HasForeignKey("SpatialUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Freehold", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Tenure", "Tenure")
                        .WithMany("Freeholds")
                        .HasForeignKey("TenureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Group", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Owner", "Owner")
                        .WithMany("Groups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.GroupGroupLeadership", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.GroupLeadership", "GroupLeadership")
                        .WithMany("GroupGroupLeadership")
                        .HasForeignKey("GroupLeadershipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.GroupGroupMembership", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.GroupMembership", "GroupMembership")
                        .WithMany("GroupGroupMemberships")
                        .HasForeignKey("GroupMembershipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.InstitutionInstitutionLeadership", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Institution", "Institution")
                        .WithMany("InstitutionInstitutionLeadership")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.InsitutionLeadership", "InstitutionLeadership")
                        .WithMany("InstitutionInstitutionLeadership")
                        .HasForeignKey("InstitutionLeadershipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.LandUse", b =>
                {
                    b.HasOne("LIMS.Core.Entities.BuildingRegulation", "BuildingRegulation")
                        .WithMany("LandUses")
                        .HasForeignKey("BuildingRegulationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Zone", "Zone")
                        .WithMany("LandUses")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Leasehold", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Tenure", "Tenure")
                        .WithMany("Leaseholds")
                        .HasForeignKey("TenureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Operation", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Parcel", "Parcel")
                        .WithMany("Operations")
                        .HasForeignKey("ParcelId")
                        .HasConstraintName("FK_Operation_Parcel")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Parcel", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Administration", "Administration")
                        .WithMany("Parcels")
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.LandUse", "LandUse")
                        .WithMany("Parcels")
                        .HasForeignKey("LandUseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Owner", "Owner")
                        .WithMany("Parcels")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.OwnershipRight", "OwnershipRight")
                        .WithMany("Parcels")
                        .HasForeignKey("OwnershipRightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Rate", "Rate")
                        .WithMany("Parcels")
                        .HasForeignKey("RateId");

                    b.HasOne("LIMS.Core.Entities.Registration", "Registration")
                        .WithMany("Parcels")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Responsibility", "Responsibility")
                        .WithMany("Parcels")
                        .HasForeignKey("ResponsibilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Restriction", "Restriction")
                        .WithMany("Parcels")
                        .HasForeignKey("RestrictionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.SpatialUnit", "SpatialUnit")
                        .WithMany("Parcels")
                        .HasForeignKey("SpatialUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Tenure", "Tenure")
                        .WithMany("Parcels")
                        .HasForeignKey("TenureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Valuation", "Valuation")
                        .WithMany("Parcels")
                        .HasForeignKey("ValuationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Person", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Owner", "Owner")
                        .WithMany("Persons")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.PersonGroupLeadership", b =>
                {
                    b.HasOne("LIMS.Core.Entities.GroupLeadership", "GroupLeadership")
                        .WithMany("PersonGroupLeaderships")
                        .HasForeignKey("GroupLeadershipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Person", "Person")
                        .WithMany("PersonGroupLeaderships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.PersonGroupMembership", b =>
                {
                    b.HasOne("LIMS.Core.Entities.GroupMembership", "GroupMembership")
                        .WithMany("PersonGroupMemberships")
                        .HasForeignKey("GroupMembershipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Person", "Person")
                        .WithMany("PersonGroupMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.PersonInstitutionLeadership", b =>
                {
                    b.HasOne("LIMS.Core.Entities.InsitutionLeadership", "InstitutionLeadership")
                        .WithMany("PersonInstitutionLeaderships")
                        .HasForeignKey("InstitutionLeadershipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Person", "Person")
                        .WithMany("PersonInstitutionLeaderships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.Restriction", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Charge", "Charge")
                        .WithMany("Restrictions")
                        .HasForeignKey("ChargeId")
                        .HasConstraintName("FK_Restriction_Charge");

                    b.HasOne("LIMS.Core.Entities.Mortgage", "Mortgage")
                        .WithMany("Restrictions")
                        .HasForeignKey("MortgageId")
                        .HasConstraintName("FK_Restriction_Mortgage");

                    b.HasOne("LIMS.Core.Entities.Reserve", "Reserve")
                        .WithMany("Restrictions")
                        .HasForeignKey("ReserveId")
                        .HasConstraintName("FK_Restriction_Reserve");

                    b.HasOne("LIMS.Core.Entities.StatutoryRestriction", "StatutoryRestriction")
                        .WithMany("Restrictions")
                        .HasForeignKey("StatutoryRestrictionId")
                        .HasConstraintName("FK_Restriction_StatutoryRestriction");
                });

            modelBuilder.Entity("LIMS.Core.Entities.Service", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Operation", "Operation")
                        .WithMany("Services")
                        .HasForeignKey("OperationId")
                        .HasConstraintName("FK_Service_Operation");
                });

            modelBuilder.Entity("LIMS.Core.Entities.SpatialUnit", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Boundary", "Boundary")
                        .WithOne("SpatialUnit")
                        .HasForeignKey("LIMS.Core.Entities.SpatialUnit", "BoundaryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.MapIndex", "MapIndex")
                        .WithMany("SpatialUnits")
                        .HasForeignKey("MapIndexId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.SpatialUnitSet", "SpatialUnitSet")
                        .WithMany("SpatialUnits")
                        .HasForeignKey("SpatialUnitSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.Survey", "Survey")
                        .WithMany("SpatialUnits")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LIMS.Core.Entities.SpatialUnitSetRegistration", b =>
                {
                    b.HasOne("LIMS.Core.Entities.Registration", "Registration")
                        .WithMany("SpatialUnitSetRegistrations")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Core.Entities.SpatialUnitSet", "SpatialUnitSet")
                        .WithMany("SpatialUnitSetRegistrations")
                        .HasForeignKey("SpatialUnitSetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LIMS.Infrastructure.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LIMS.Infrastructure.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LIMS.Infrastructure.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LIMS.Infrastructure.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
